name: tag-publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Check package
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      working-directory: ./
      tooling: golang
      tooling-version: 1.20.x
      target-build: false
      target-lint: false
      target-unit-tests: true

  publish:
    name: Publish to npmjs.org
    runs-on: ubuntu-latest
    needs: build
    environment: npmjs-registry
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x          
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: make build
      - run: make deploy
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
